/* prettier-ignore */

const Products = [
  {
    id: 1,
    name: 'Combo Britney',
    category: 'Combo',
    img: 'https://i.postimg.cc/P5nBLgV2/Combo.png',
    price: 40,
    description: 'Hamburguer de frango, refrigerante e batata-frita',
  },
  {
    id: 2,
    name: 'Combo Lady Gaga',
    category: 'Combo',
    img: 'https://i.postimg.cc/8PrZZ3bJ/outravaquinha.png',
    price: 50,
    description: 'Hambúrguer bovino, refrigerante e batata-frita',
  },
  {
    id: 3,
    name: 'Combo Luisa Mell',
    category: 'Combo',
    img: 'https://i.postimg.cc/YCLjGNMw/vaquinha.png',
    price: 55,
    description: 'Hambúrguer vegetariano, refrigerante e batata-frita',
  },
  {
    id: 4,
    name: 'Combo Gisele Bündchen',
    category: 'Combo',
    img: 'https://i.postimg.cc/Pf4Gxr15/giseleb.png',
    price: 40,
    description: 'Sanduíche integral, suco e chips de batata doce',
  },
  {
    id: 5,
    name: 'Frango Marombeiro',
    category: 'Acompanhamento',
    img: 'https://i.postimg.cc/mrnbDZ9n/frango.png',
    price: 30,
    description: 'Tiras de frango empanado',
  },
  {
    id: 6,
    name: 'Cebola Outbêco',
    category: 'Acompanhamento',
    img: 'https://i.postimg.cc/wB2qdcx9/cebola.png',
    price: 25,
    description: 'Cebola empanada',
  },
  {
    id: 7,
    name: 'Batata de Marechal',
    category: 'Acompanhamento',
    img: 'https://i.postimg.cc/mrjX4VcZ/batatamarechal.png',
    price: 25,
    description: 'Batata Frita turbinada',
  },
  {
    id: 8,
    name: 'Batata Caio Castro',
    category: 'Acompanhamento',
    img: 'https://i.postimg.cc/5t8JShk7/batatacaio.png',
    price: 15,
    description: 'Batata frita baratinha',
  },
  {
    id: 9,
    name: 'Refrigerante',
    category: 'Bebida',
    img: 'https://i.postimg.cc/TYZYjJ3P/refrilata.png',
    price: 8,
    description: 'Refrigerante em lata',
  },
  {
    id: 10,
    name: 'Suco',
    category: 'Bebida',
    img: 'https://i.postimg.cc/DfR85TCF/suco.png',
    price: 8,
    description: 'Suco natural',
  },
  {
    id: 11,
    name: 'Açaí',
    category: 'Sobremesa',
    img: 'https://i.postimg.cc/JnCfX9h1/acai.png',
    price: 15,
    description: 'Açaí turbinado',
  },
  {
    id: 12,
    name: 'Torta de Climão',
    category: 'Sobremesa',
    img: 'https://i.postimg.cc/rptrqwZh/tortadelimao.png',
    price: 13,
    description: 'Torta sabor limão',
  },
];

export default Products;
